# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  setup:
    sources:
      - '*.json'
    cmds:
      - pnpm i
  fmt:
    cmds:
      - pnpm biome format --write

  lint:
    cmds:
      - pnpm biome lint --write

  build:
    sources:
      - 'src/**/*.ts'
      - '*.json'
    cmds:
      - node esbuild.ts
      - pnpm vsce package -o dist/extension.vsix --no-dependencies

  default:
    deps:
      - fmt
      - lint
      - build
    silent: true
