# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  fmt:
    sources:
      - '**/*.go'
      - 'Taskfile.yml'
    cmds:
      - go fmt

  lint:
    sources:
      - '**/*.go'
      - 'Taskfile.yml'
    cmds:
      - golangci-lint run

  build:
    sources:
      - '**/*.go'
      - 'Taskfile.yml'
    cmds:
      - go build -o dist/path-intellisense-lsp

  default:
    deps:
      - fmt
      - lint
      - build
